=== SOLARIS-Collective/Solaris/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"pattern": "-class",
			"description": "The name of the ship class, as viewable in-game. The -class suffix must be lowercase."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"pattern": "-class$",
			"description": "A shortened version of the ship class name, used in things such as the manifest. The -class suffix must be lowercase, and the end of the value.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future.",
			"minLength": 250
		},


		"sensor_range":{
			"title": "Sensor Range",
			"type": "number",
			"description": "A definition of a ships' maximum sensor range."
		},


		"tags": {
			"title": "Ship Tags",
			"type": "array",
			"description": "A list of tags describing the ship's niche, converted into searchable strings."
		},
		"faction": {
			"title": "Ship Faction Datum",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"default": "/datum/faction/independent",
			"description": "The path of the ship's original faction datum. If null, the ship will be considered independent."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": ["null", "string"],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"manufacturer": {
			"title": "Ship Manufacturer",
			"type": ["null", "string"],
			"description": "The manufacturer of the ship class, used in autowiki templates."
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CLIP-BARD",
					"PGF"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"starting_funds": {
			"title": "Ship Starting Funds",
			"Type": "integer",
			"description": "The amount of money a ship's bank account starts with",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"omni_arpa": {
			"title": "Omni ARPA",
			"type": "boolean",
			"description": "If true, this ship's helm uses the classic ARPA: it sees the real names of all ships at range and has no label buttons. Intended for spy/artillery-type ships.",
			"default": false
		},
		"spawn_time_coeff": {
			"title": "Required Spawn Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value SHIP_SPAWN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn this ship from the join menu.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Required Officer Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value OFFICER_JOIN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn as an officer job on this ship AFTER it has been spawned.",
			"minimum": 0,
			"default": 1
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		},
		"space_spawn": {
			"title": "Spawns in space",
			"type": "boolean",
			"description": "Whether this ship will spawn in space or at the outpost. If true, the ship will be placed randomly in space upon being spawned by the join menu.",
			"default": false
		}
	},

	"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== SOLARIS-Collective/Solaris/_maps/_modular_solaris/configs/elysium_lalish.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Lalish-class Space Explosives Factory",
	"map_short_name": "Lalish",
	"description": "Корабли класса 'Лалиш' — это относительно недавно спроектированные и построенные на верфях сепаратистов Элизиума суда. Их основное назначение — производство взрывчатых веществ, таких как бомбы, гранаты и пластиковая взрывчатка... Для этого на борту предусмотрено все необходимое: химические реактивы, материалы, камера сгорания и прочее. Судно имеет компактные размеры, что делает его менее заметным, однако это негативно сказалось на удобстве планировки. Кроме того, его двигательная установка оставляет желать лучшего — корабль оснащен всего двумя ионными двигателями, которые с трудом справляются с его массой. В итоге мы имеем небольшой, малоскоростной, но все же способный передвигаться корабль с минимальным экипажем, вооруженным верой в Аллаха и взрывчаткой. Слава Республике! – Алмаждурин Джанхуриети!",
	"map_path": "_maps/_modular_solaris/shuttles/elysium/elysium_lalish.dmm",
	"enabled": true,
	"limit": 1,
	"prefix": "ESV",
	"faction": "/datum/faction/elysium",
	"tags": [
		"Специализированный",
		"РП Фокус",
		"Выживание"
	],
	"namelists": [
		"SPACE",
		"MAGICAL"
	],
	"job_slots": {
		"Caid": {
			"outfit": "/datum/outfit/job/cel/elysium/captain",
			"officer": true,
			"slots": 1
		},
		"Ahisa`i": {
			"outfit": "/datum/outfit/job/cel/elysium/assistant",
			"slots": 3
		}

	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/independent_tranquility.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Tranquility-class Flying Apartment Complex",
	"map_short_name": "Tranquility",
	"description": "Большинство суден имеют четкое назначение - исследовательские, добывающие, грузовые и так далее - но класс 'Tranquility' является заметным исключением из этого правила. 'Tranquility' - довольно спокойное и уравновешенное судно, созданное по образцу традиционных жилых комплексов. Оснащенные несколькими независимыми каютами, большой общей столовой и очень малым количеством промышленного оборудования или средств самообороны, судна класса 'Tranquility' часто можно встретить лениво курсирующими по Фронтиру, устраивающими ситкомовские выходки и отказывающимися от более целенаправленного подхода многих своих современников.",
	"map_path": "_maps/shuttles/independent/independent_tranquility.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 8,
	"prefix": "ЕSV",
	"faction": "/datum/faction/independent",
	"tags": [
		"РП Фокус",
		"Сервисный"
	],
	"namelists": [
		"GENERAL",
		"SPACE",
		"NATURAL"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/independent/captain/western",
			"officer": true,
			"slots": 1
		},
		"Scholar": {
			"outfit": "/datum/outfit/job/cel/independent/curator",
			"slots": 1
		},
		"Medical Tenant": {
			"outfit": "/datum/outfit/job/cel/independent/chemist",
			"slots": 1
		},
		"Engineering Tenant": {
			"outfit": "/datum/outfit/job/cel/independent/engineer",
			"slots": 1
		},
		"Tenant": {
			"outfit": "/datum/outfit/job/cel/independent/curator/dungeonmaster",
			"slots": 1
		},
		"Resident Artist": {
			"outfit": "/datum/outfit/job/cel/independent/assistant/artist",
			"slots": 1
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_solaris/configs/nanotrasen_skipper.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_modular_solaris/ship_config_schema.json",
	"map_name": "Skipper-class Heavy Cruiser",
	"map_short_name": "Skipper",
	"description": "Пример одного из крейсеров Нанотрейзена 'стандартного образца'. По меркам Фронтира судно класса 'Skipper' хорошо оснащено: достаточно места для инженерного оборудования, хорошо оборудованные места для экипажа и приличный запас оборонительного вооружения. Примечательно, что на 'Skipper' больше, чем в среднем, командный отсек, а офицеры на 'Skipper', как правило, лучше оснащены, чем их коллеги. Хотя должность на борту 'Osprey' не так престижна, как на 'Нанотрейзене', мало кто из капитанов откажется от командования 'Skipper'.",
	"map_path": "_maps/_modular_solaris/shuttles/nanotrasen/nanotrasen_skipper.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"starting_funds": 4500,
	"prefix": "NTSV",
	"faction": "/datum/faction/nt",
	"tags": [
		"Engineering",
		"Mining"
	],
	"namelists": [
		"NANOTRASEN",
		"SPACE",
		"MYTHOLOGICAL",
		"WEAPONS",
		"MERCANTILE"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/captain",
			"officer": true,
			"slots": 1
		},
		"First Officer": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/hop",
			"officer": true,
			"slots": 1
		},
		"Supply Director": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/quartermaster",
			"officer": true,
			"slots": 1
		},
		"Security Director": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/hos",
			"officer": true,
			"slots" : 1
		},
		"Security Officer": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/security",
			"slots": 2
		},
		"Medical Specialist": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/doctor",
			"slots": 1
		},
		"Ship's Engineer": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/engineer",
			"slots": 1
		},
		"Atmospheric Technician": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/atmos",
			"slots": 1
		},
		"Shaft Miner": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/miner",
			"slots": 2
		},
		"Cook": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/cook",
			"slots": 1
		},
		"Bartender": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/bartender",
			"slots": 1
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/assistant",
			"slots": 2
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/pirate_stingray.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/ship_config_schema.json",
	"map_name": "Stingray-class Scouting Ship",
	"map_short_name": "Stingray",
	"description": "Судно класса 'Stingray' представляет собой реконструированную модель Clandestine 2 поколения типа 'Покоритель космоса'. Изначальная модель зарекомендовала себя как один из лучших представителей своего класса и имела огромный спрос. Однако компания-производитель сменила вектор деятельности, из-за чего производство судов было прекращено. Большинство сохранившихся моделей до сих пор находятся в рабочем состоянии, хотя их эксплуатационный срок службы давно превысил предписанные лимиты. Некоторым пиратам удалось получить пару рабочих экземпляров в свое владение, а после переоборудовать их под личные нужды.",
	"map_path": "_maps/shuttles/pirate/pirate_stingray.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 9,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Выживание"
	],
	"namelists": [
		"PIRATES",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Defector Commander": {
			"outfit": "/datum/outfit/job/cel/pirate/captain/stingray",
 			"officer": true,
			"slots": 1
		},
			"Defector Radioman": {
			"outfit": "/datum/outfit/job/cel/pirate/hop/stingray",
			"officer": true,
			"slots": 1
		},
			"Defector Officer": {
			"outfit": "/datum/outfit/job/cel/pirate/security/stingray",
			"officer": true,
			"slots": 1
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_solaris/configs/nanotrasen_osprey.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Osprey-class Exploration Cruiser",
	"map_short_name": "Osprey",
	"description": "Одни из самых современных суден флота Нанотрейзен и престижное задание для их капитанов, знаменитые 'Osprey', участвовавшие в самых драматических астронавигационных столкновениях ICW, продолжают жить в качестве очень хорошо оборудованного исследовательского судна. Прошедшие значительную модернизацию после того, как они стали артиллерийскими платформами Bluespace, современные Osprey используют сенсорное оборудование военного класса и системы искусственного интеллекта для разведки и научной работы. Среди особенностей - хорошо оснащенные медицинские, кулинарные и научные помещения и ядро ИИ, а также общекорабельная система утилизации и доставки и очень вместительный грузовой отсек. Однако мощные (хотя и нестабильные) двигатели на суперматерии, которые приводили в движение первые партии 'Osprey', были вычеркнуты при их реконструкции, а заменяющие их генераторы оставили современные 'Osprey' в состоянии некоторой нехватки энергии. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Заменен на Целестис!",
	"map_path": "_maps/_modular_solaris/shuttles/nanotrasen/nanotrasen_osprey.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 9,
	"starting_funds": 4000,
	"prefix": "NTRSV",
	"faction": "/datum/faction/nt",
	"tags": ["Исследовательский", "ИИ"],
	"namelists": [
		"NANOTRASEN",
		"SPACE",
		"MYTHOLOGICAL",
		"WEAPONS"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/captain",
			"officer": true,
			"slots": 1
		},
		"Science Director": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/rd",
			"officer": true,
			"slots": 1
		},
		"Scientist": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/scientist",
			"slots": 2
		},
		"Medical Doctor": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/doctor",
			"slots": 1
		},
		"Paramedic": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/paramedic",
			"slots": 1
		},
		"Engineer": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/engineer",
			"slots": 1
		},
		"Atmospheric Technician": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/atmos",
			"slots": 1
		},
		"Shaft Miner": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/miner",
			"slots": 2
		},
		"Cook": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/cook",
			"slots": 1
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/assistant",
			"slots": 2
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_mankind/configs/inteq_talos.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Talos-class Command Clipper",
	"map_short_name": "Talos",
	"description": "'Talos' - это судно поддержки и командования, редкий пример специально построенного корабля InteQ. Оснащенные обилием строительного и инженерного оборудования, а также собственным комплексом связи в блюспейсе, способным объединить корабли IRMG в любой системе, 'Talos' часто являются связующим звеном скоординированных операций IRMG в системе и предлагают услуги по строительству и ремонту в качестве части предложения наемников IRMG. Поскольку экипажи 'Talos' делают больший упор на вспомогательный персонал, они, как правило, не так хорошо вооружены по сравнению с другими экипажами InteQ, хоть и обладают мехом с боевым оснащением. Одна из необычных особенностей 'Talos' - 'крылья' с дублирующими перегородками, призванные обеспечить дополнительную прочность в случае ударов или выстрелов. Кроме того, они служат дополнительным местом для хранения вещей и потенциальным местом для модификации корабля предприимчивыми инженерами, которые здесь являются необходимой частью экипажа.",
	"map_path": "_maps/_modular_mankind/shuttles/inteq/inteq_talos.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range":5,
	"prefix": "IRMV",
	"faction": "/datum/faction/inteq",
	"tags": [
		"Инженерное",
		"Шахтерский",
		"РП Фокус"
	],
	"namelists": [
		"MYTHOLOGICAL",
		"BEASTS",
		"NATURAL_AGGRESSIVE",
		"INTEQ"
	],
	"job_slots": {
		"Vanguard": {
			"outfit": "/datum/outfit/job/cel/inteq/captain",
			"officer": true,
			"slots": 1
		},
		"Master At Arms": {
			"outfit": "/datum/outfit/job/cel/inteq/warden",
			"officer": true,
			"slots": 1
		},
		"Artificer Class II": {
			"outfit": "/datum/outfit/job/cel/inteq/ce",
			"officer": true,
			"slots": 1
		},
		"Artificer": {
			"outfit": "/datum/outfit/job/cel/inteq/engineer",
			"slots": 3
		},
		"Corpsman": {
			"outfit": "/datum/outfit/job/cel/inteq/paramedic",
			"slots": 2
		},
		"Enforcer": {
			"outfit": "/datum/outfit/job/cel/inteq/security",
			"slots": 3
		},
		"Recruit": {
			"outfit": "/datum/outfit/job/cel/inteq/assistant",
			"slots": 2
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_mankind/configs/pirate_ember.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_modular_mankind/ship_config_schema.json",
	"map_name": "Ember-class Pirate Raider",
	"map_short_name": "Ember",
	"description": "Судно класса 'Ember' - это красный флаг в любом секторе. Гигантское, медленно движущееся, опасное в плане безопасности судно, самодельный почти во всех отношениях, пользуется благосклонностью самых безжалостных и жестоких пиратов и негодяев по всей галактике. Простое желание существовать на одном из этих суден - свидетельствует о выносливости, которая обычно не свойственна большинству жителей космоса. Лучший способ иметь дело с суднами 'Ember' - просто обходить их стороной. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: Пираты - Имеет сильное вооружение, является Дредноутом пиратов по типу Твинклшайна или Херона. Для ивентов шип.",
	"map_path": "_maps/_modular_mankind/shuttles/pirate/pirate_ember.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 3,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Боевой"
	],
	"namelists": [
		"PIRATES",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/pirate/captain",
			"officer": true,
			"slots": 1
		},
		"Bridge Officer": {
			"outfit": "/datum/outfit/job/cel/pirate/hop",
			"officer": true,
			"slots": 2
		},
		"Shipswain": {
			"outfit": "/datum/outfit/job/cel/pirate/hos",
			"officer": true,
			"slots": 1
		},
		"Senior Sapper" :{
			"outfit": "/datum/outfit/job/cel/pirate/frontiersmen/ce",
			"officer": true,
			"slots": 1
		},
		"Cargo Tech": {
			"outfit": "/datum/outfit/job/cel/pirate/frontiersmen/cargo_tech",
			"slots": 2
		},
		"Aidman": {
			"outfit": "/datum/outfit/job/cel/pirate/medic",
			"slots": 1
		},
		"Sapper": {
			"outfit": "/datum/outfit/job/cel/pirate/engineer",
			"slots": 2
		},
		"Atmospheric Technician": {
			"outfit": "/datum/outfit/job/cel/pirate/frontiersmen/atmos",
			"slots": 1
		},
		"Steward": {
			"outfit": "/datum/outfit/job/cel/pirate/cook",
			"slots": 1
		},
		"Boarder": {
			"outfit": "/datum/outfit/job/cel/pirate/security",
			"slots": 3
		},
		"Rookie": {
			"outfit": "/datum/outfit/job/cel/pirate/assistant",
			"slots": 3
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_mankind/configs/independent_mimos.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Mimos - class civil ship",
	"map_short_name": "Mimos",
	"description": "Гражданское судно нестандартной конструкции. Экипаж известен как профессиональный цирк мимов и клоунов, хотя и былая слава далеко позади. Хоть судно уже далеко не новое, но все еще исправно служит своим владельцам домом и защитой.",
	"map_path": "_maps/_modular_mankind/shuttles/independent/independent_mimos.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 7,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Специализированный",
		"Сервисный",
		"РП Фокус"
	],
	"namelists": [
		"GENERAL",
		"SPACE"
		],
	"job_slots": {
		"Master Mime": {
			"outfit": "/datum/outfit/job/cel/independent/mime/captain",
			"officer": true,
			"slots": 1
		},
		"Lower deck Mime": {
			"outfit": "/datum/outfit/job/cel/independent/mime",
			"officer": true,
			"slots": 4
		},
		"Maintenance Clown": {
			"outfit": "/datum/outfit/job/cel/independent/clown/maintenanceclown",
			"slots": 1
		}
	}
}
