=== SOLARIS-Collective/Solaris/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"pattern": "-class",
			"description": "The name of the ship class, as viewable in-game. The -class suffix must be lowercase."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"pattern": "-class$",
			"description": "A shortened version of the ship class name, used in things such as the manifest. The -class suffix must be lowercase, and the end of the value.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future.",
			"minLength": 250
		},


		"sensor_range":{
			"title": "Sensor Range",
			"type": "number",
			"description": "A definition of a ships' maximum sensor range."
		},


		"tags": {
			"title": "Ship Tags",
			"type": "array",
			"description": "A list of tags describing the ship's niche, converted into searchable strings."
		},
		"faction": {
			"title": "Ship Faction Datum",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"default": "/datum/faction/independent",
			"description": "The path of the ship's original faction datum. If null, the ship will be considered independent."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": ["null", "string"],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"manufacturer": {
			"title": "Ship Manufacturer",
			"type": ["null", "string"],
			"description": "The manufacturer of the ship class, used in autowiki templates."
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CLIP-BARD",
					"PGF"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"starting_funds": {
			"title": "Ship Starting Funds",
			"Type": "integer",
			"description": "The amount of money a ship's bank account starts with",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"omni_arpa": {
			"title": "Omni ARPA",
			"type": "boolean",
			"description": "If true, this ship's helm uses the classic ARPA: it sees the real names of all ships at range and has no label buttons. Intended for spy/artillery-type ships.",
			"default": false
		},
		"spawn_time_coeff": {
			"title": "Required Spawn Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value SHIP_SPAWN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn this ship from the join menu.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Required Officer Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value OFFICER_JOIN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn as an officer job on this ship AFTER it has been spawned.",
			"minimum": 0,
			"default": 1
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		},
		"space_spawn": {
			"title": "Spawns in space",
			"type": "boolean",
			"description": "Whether this ship will spawn in space or at the outpost. If true, the ship will be placed randomly in space upon being spawned by the join menu.",
			"default": false
		}
	},

	"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== SOLARIS-Collective/Solaris/_maps/_modular_mankind/configs/syndicate_luxembourg.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_modular_mankind/ship_config_schema.json",
	"map_name": "Luxembourg-class Delivery Vessel",
	"map_short_name": "Luxembourg",
	"description": "Судно двойного назначения: доставка и продажа. Судно класса 'Luxembourg' составляет значительную часть флота Donk! Co. на границе, где вечно-оппортунистская корпорация начала заполнять пробелы, оставшиеся после краха логистической сети Nanotrasen. Менеджеры Donk! Co. обладают большой степенью автономии, и поэтому в любом конкретном корабле 'Luxembourg' часто приходится вносить существенные изменения в торговый зал и бортовое кафе, чтобы лучше привлекать новых клиентов в нестабильном, но прибыльном регионе пространства.",
	"map_path": "_maps/_modular_mankind/shuttles/syndicate/syndicate_luxembourg.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 3,
	"starting_funds": 6000,
	"prefix": "TSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Торговый", "РП Фокус"],
	"namelists": [
		"DONK",
		"MERCANTILE",
		"SPACE"
	],
	"job_slots": {
		"Manager": {
			"outfit": "/datum/outfit/job/cel/syndicate/quartermaster/donk",
			"slots": 1
		},
		"Customer Service Representative": {
			"outfit": "/datum/outfit/job/cel/syndicate/cargo_tech/donk",
			"slots": 5
		},
		"Food and Beverage Specialist": {
			"outfit": "/datum/outfit/job/cel/syndicate/bartender",
			"slots": 1
		},
		"GEC Contracted Engineer": {
			"outfit": "/datum/outfit/job/cel/syndicate/engineer/gec",
			"slots": 1
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/syndicate_gorlex_howl.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_modular_solaris/ship_config_schema.json",
	"map_name": "Howler-class easy Warship ",
	"map_short_name": "Howl",
	"description": " «Howl» — созданный корабль на...",
	"map_path": "_maps/shuttles/syndicate/syndicate_gorlex_howl.dmm",
	"enabled" : true,
	"limit": 1,
	"sensor_range": 7,
	"faction": "/datum/faction/syndicate",
	"prefix": "BSSV",
	"tags": [
		"Боевой"
	],
	"namelists": [
		"GORLEX",
		"NATURAL_AGGRESSIVE",
		"BEASTS",
		"WEAPONS",
		"ACLF"
	],
	"job_slots": {
		"Commander": {
			"outfit": "/datum/outfit/job/cel/syndicate/captain",
			"officer": true,
			"slots": 1
		},
		"Hardliner Consultant": {
			"outfit": "/datum/outfit/job/cel/syndicate/captain/gorlex",
			"officer": true,
			"slots": 1
		},
		"hardliner Operatives": {
			"outfit": "/datum/outfit/job/cel/syndicate/security/gorlex",
			"slots": 2
		},
		"Combat Medic": {
			"outfit": "/datum/outfit/job/cel/syndicate/doctor",
			"slots": 1
		},
		"Combat Mechanic": {
			"outfit": "/datum/outfit/job/cel/syndicate/engineer",
			"slots": 1
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_solaris/configs/syndicate_gorlex_beetle.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_modular_solaris/ship_config_schema.json",
	"map_name": "Beetle-class Battle Schnau",
	"map_short_name": "Beetle",
	"description": "Боевое судно класса Beetle- Небольшое судно используемое Горлексом для поддержки в бою или мелких рейдах. Было разработано при поддержке киберсан для создания манёвренного судна для быстрых операций, в качестве эксперимента экипаж был оснащён лазерным вооружением.",
	"map_path": "_maps/_modular_solaris/shuttles/syndicate/syndicate_gorlex_beetle.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "BSSV",
	"faction": "/datum/faction/syndicate",
	"tags": ["Боевой"],
	"namelists": [
		"GORLEX",
		"NATURAL_AGGRESSIVE",
		"BEASTS",
		"WEAPONS",
		"ACLF"
	],
	"job_slots": {
		"Squad leader": {
			"outfit": "/datum/outfit/job/cel/syndicate/captain/gorlex",
			"officer": true,
			"slots": 1,
			"name": "Gorlex Squad leader"
		},
		"Paramedic": {
			"outfit": "/datum/outfit/job/cel/syndicate/doctor/gorlex",
			"slots": 1,
			"name": "Paramedic"
		},
		"Mechanic": {
			"outfit": "/datum/outfit/job/cel/syndicate/engineer/gorlex",
			"slots": 1

		},
		"Operative": {
			"outfit": "/datum/outfit/job/cel/syndicate/security/gorlex",
			"slots": 3
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/nanotrasen_savior.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Savior-class multifunctional medical ship",
	"map_short_name": "Savior",
	"description": "Многофункциональное медицинское судно класса 'Savior' является одной из новейших разработок компании Nanotrasen. Оно спроектировано для оказания всесторонней медицинской помощи в условиях космоса. Судно оснащено современным медицинским оборудованием и системами жизнеобеспечения, что позволяет оперативно и эффективно реагировать на различные медицинские чрезвычайные ситуации. Благодаря своей универсальности, судно 'Savior' может использоваться как для спасательных операций, так и для проведения длительных медицинских экспедиций.",
	"map_path": "_maps/shuttles/nanotrasen/nanotrasen_savior.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 9,
	"prefix": "NTMSV",
	"faction": "/datum/faction/nt",
	"tags": [
		"Исследовательский",
		"Медицинское"
	],
	"namelists": [
		"GENERAL",
		"SPACE",
		"NANOTRASEN"
	],
	"job_slots": {
		"Medical Director": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/captain/deforest_captain",
			"officer": true,
			"slots": 1
		},
		"Engineer": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/engineer/nakamura",
			"slots": 1
		},
		"Medical Doctor": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/doctor/deforest_medic",
			"slots": 2
		},
		"Chemist": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/chemist/deforest_chemist",
			"slots": 1
		},
		"Genetical Researcher": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/scientist/deforest_researcher/genetic",
			"slots": 1
		},
		"Paramedic": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/paramedic/deforest_medic",
			"slots": 1
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_mankind/configs/pirate_rondo.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Rondo-class Renegade Assault Vessel",
	"map_short_name": "Rondo",
	"description": "'Rondo' - Cудно ранее используемое синдикатом как разведывательное, изначально снабжалось системой оптического камуфляжа. Однако из-за несовершенства технологии, любое повреждение экранирования приводило к полному отключению систем, в связи с чем судну требовался длительный ремонт. Ко всему прочему, использование технологии оптического камуфляжа, а тем более его ремонт требовали высокую степень квалификации экипажа, в результате чего система камуфляжа была снята, а сами суда из-за своей малой эффективности отправлены на утилизацию в верфи конструкторского бюро. От полного уничтожения данные суда были спасены во время рейда группировкой Рамзи, благодаря чему некоторые экземпляры попали на черный рынок, а оставшиеся до сих пор находятся во владении некоторых боевых формирований, в том числе и Ренегатов.",
	"map_path": "_maps/_modular_mankind/shuttles/pirate/pirate_rondo.dmm",
	"enabled" : true,
	"limit": 1,
	"sensor_range": 13,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Боевой",
		"Выживание"
	],
	"namelists": [
		"PIRATES",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Battle Master": {
			"outfit": "/datum/outfit/job/cel/pirate/ramzi/captain",
			"officer": true,
			"slots": 1
		},
		"Commando": {
			"outfit": "/datum/outfit/job/cel/pirate/ramzi/trooper",
			"slots": 4
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/pirate_libertatia.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/ship_config_schema.json",
	"map_name": "Libertatia-class Hauler",
	"map_short_name": "Libertatia",
	"description": "Широкодоступный и дешевый курьерское судно компании Miskilamo Spacefaring 'Libertatia' представляет собой некачественный ремонт старых гражданских атмосферных суден или сгоревших обломков других 'Libertatia', которые становятся номинально пригодными для космоса и способны перевозить скромный груз на огромных скоростях. Хотя Libertatia продавалась как курьерское судно и грузовой шаттл малой дальности, её истинным рынком сбыта стали контрабандисты, блокадники и пираты, которые нашли ее скорость и низкую цену - чрезвычайно привлекательными. В последние годы пираты стали гораздо чаще управлять 'Libertatias', чем кто-либо другой. Данная же 'Libertatia' попала в руки пиратов - абордажников, специализирующихся на нелетальном захвате целей, с их последующей перепродажей или в качестве рычагов давления на конкурентов.",
	"map_path": "_maps/shuttles/pirate/pirate_libertatia.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 8,
	"space_spawn": true,
	"prefix": "RSV",
	"faction": "/datum/faction/pirate",
	"tags": [
		"Специализированный",
		"Боевой"
	],
	"namelists": [
		"PIRATES",
		"NATURAL_AGGRESSIVE"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/pirate/captain",
			"officer": true,
			"slots": 1
		},
		"Buccaneer": {
			"outfit": "/datum/outfit/job/cel/pirate/security",
			"slots": 2
		},
		"Motorman": {
			"outfit": "/datum/outfit/job/cel/pirate/engineer",
			"slots": 1
		},
		"Ship's Doctor": {
			"outfit": "/datum/outfit/job/cel/pirate/medic",
			"slots": 1
		},
		"Deckhand": {
			"outfit": "/datum/outfit/job/cel/pirate/assistant",
			"slots": 2
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/elysium_aldaama.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Aldaama-class Experimental Project",
	"map_short_name": "Aldaama",
	"description": "Изначально 'Алдаама' работал на двигателе Сингулярности, но после ее побега, никто даже не заикался снова ввести ее в эксплуатацию. Вместо этого сделали более безопасный двигатель Тесла. На данный момент у Республики Элизиума всего два таких корабля. Один стоит в музее 'Алехар'(каменистая планета 'Лер'), а второй активно используется сепаратистами Элизиума как корабль снабжения и оперативной телекоммуникационной базой.",
	"map_path": "_maps/shuttles/elysium/elysium_aldaama.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ESV",
	"faction": "/datum/faction/elysium",
	"tags": [
		"Специализированный",
		"Боевой",
		"РП Фокус"
	],
	"namelists": [
		"SPACE",
		"WEAPONS",
		"ENGINEERING"
	],
	"job_slots": {
		"Caid": {
			"outfit": "/datum/outfit/job/cel/elysium/captain",
			"officer": true,
			"slots": 1
		},
		"Ahisa`i": {
			"outfit": "/datum/outfit/job/cel/elysium/assistant",
			"slots": 3
		},
		"Mukatell": {
			"outfit": "/datum/outfit/job/cel/elysium/security",
			"slots" : 2
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_solaris/configs/independent_rube_goldberg.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Rube Goldberg-class Engineering Project",
	"map_short_name": "Rube-Goldberg",
	"description": "Инженерный проект класса 'Rube Goldberg' - это опыт и памятник безумию. Мощный двигатель из сверхматерии в сочетании с эшеровской конструкцией, сложной сетью труб и проводов и полным пренебрежением к элементарным процедурам безопасности и здравому смыслу делают это судно катастрофой, которая только и ждет, чтобы случиться. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: В щитспавне по причине: Очень сложный экперементальный шип, спавнить только на свой страх и риск!",
	"map_path": "_maps/_modular_solaris/shuttles/independent/independent_rube_goldberg.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": ["Инженерный"],
	"namelists": [
		"GENERAL",
		"ENGINEERING"
	],
	"job_slots": {
		"Chief at Engineering": {
			"outfit": "/datum/outfit/job/cel/independent/ce",
			"officer": true,
			"slots": 1
		},
		"Chief at Boozineering": {
			"outfit": "/datum/outfit/job/cel/independent/bartender",
			"slots": 1
		},
		"Engineering Specialist": {
			"outfit": "/datum/outfit/job/cel/independent/engineer",
			"slots": 2
		},
		"Atmospheric Specialist": {
			"outfit": "/datum/outfit/job/cel/independent/atmos",
			"slots": 2
		},
		"Medical Specialist": {
			"outfit": "/datum/outfit/job/cel/independent/doctor",
			"slots": 1
		},
		"Mining Specialist": {
			"outfit": "/datum/outfit/job/cel/independent/miner",
			"slots": 2
		}
	}
}
