=== SOLARIS-Collective/Solaris/_maps/ship_config_schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"title": "Ship Configuration Schema",
	"description": "A ship configuration, used for defining new ship classes.",
	"type": "object",

	"properties": {
		"map_name": {
			"title": "Class Name",
			"type": "string",
			"pattern": "-class",
			"description": "The name of the ship class, as viewable in-game. The -class suffix must be lowercase."
		},
		"map_short_name": {
			"title": "Shortened Class Name",
			"type": "string",
			"pattern": "-class$",
			"description": "A shortened version of the ship class name, used in things such as the manifest. The -class suffix must be lowercase, and the end of the value.",
			"maxLength": 20
		},
		"description": {
			"title": "Class Description",
			"type": "string",
			"description": "A description of the ship class, currently only shown to admins on the shuttle manipulator, but will likely be shown to players before ship purchase in the future.",
			"minLength": 250
		},


		"sensor_range":{
			"title": "Sensor Range",
			"type": "number",
			"description": "A definition of a ships' maximum sensor range."
		},


		"tags": {
			"title": "Ship Tags",
			"type": "array",
			"description": "A list of tags describing the ship's niche, converted into searchable strings."
		},
		"faction": {
			"title": "Ship Faction Datum",
			"type": "string",
			"pattern": "^/datum/faction/(.*)$",
			"default": "/datum/faction/independent",
			"description": "The path of the ship's original faction datum. If null, the ship will be considered independent."
		},
		"prefix": {
			"title": "Ship Default Prefix",
			"type": ["null", "string"],
			"description": "The prefix of the ship class, appended to randomly generated names when they're first purchased.",
			"maxLength": 5
		},
		"manufacturer": {
			"title": "Ship Manufacturer",
			"type": ["null", "string"],
			"description": "The manufacturer of the ship class, used in autowiki templates."
		},
		"namelists": {
			"title": "Namelists",
			"type": "array",
			"description": "A list of namelists that this ship class will draw from when first bought to get a random name. All options can be found in the ship_names.json file.",
			"uniqueItems": true,
			"items": {
				"type": "string",
				"enum": [
					"GENERAL",
					"PIRATES",
					"BRITISH_NAVY",
					"MERCANTILE",
					"SPACE",
					"NATURAL",
					"NATURAL_AGGRESSIVE",
					"BEASTS",
					"MYTHOLOGICAL",
					"HISTORICAL",
					"WEAPONS",
					"PILLS",
					"ENGINEERING",
					"CRUISE",
					"MAGICAL",
					"STORYTELLING & TROPES",
					"NANOTRASEN",
					"INTEQ",
					"GORLEX",
					"SUNS",
					"CYBERSUN",
					"ACLF",
					"GEC",
					"DONK",
					"CLIP MINUTEMEN",
					"SAINT-ROUMAIN",
					"INSTALLATION",
					"SOLGOV",
					"CMM-GOLD",
					"CLIP-BARD",
					"PGF"
				]
			}
		},
		"map_path": {
			"title": "Map File Path",
			"type": "string",
			"description": "The path to the ship class's map file. Use forward slashes (/) for directories, and include the .dmm extension. Map files must be somewhere under the _maps folder.",
			"pattern": "^_maps/([a-zA-Z0-9_/.-]*)dmm$"
		},
		"job_slots": {
			"title": "Job Slots",
			"description": "A list of job slots that this ship class will have when placed. The First Slot will always be the 'captain' that the purchaser becomes.",
			"type": "object",
			"additionalProperties": {
				"oneOf": [
					{
						"type": "integer",
						"description": "A preset job slot, must match a job name in the code (Job names are found in the jobs' respective files)."
					},
					{
						"type": "object",
						"description": "A custom job slot, can be any name, but needs an outfit and slot count to be valid. The name is the string you are currently viewing.",
						"properties": {
							"outfit": {
								"type": "string",
								"description": "The name of the outfit that will be placed in this slot. Must be exact, will error if not found in the code.",
								"pattern": "^/datum/outfit/(.*)$"
							},
							"officer": {
								"type": "boolean",
								"description": "Whether or not this slot is an officer slot. This determines if the job will have a chevron in the manifest, as well as the amount of slots cannot be changed by the crew in-round.",
								"default": false
							},
							"slots": {
								"type": "integer",
								"description": "The number of slots that this slot will have roundstart. The crew can change this, up to doubling it, in-round.",
								"minimum": 1
							}
						},
						"required": ["outfit", "slots"]
					}
				]
			}
		},
		"limit": {
			"title": "Ship Spawning Limit",
			"type": "integer",
			"description": "The amount of ships that can be spawned in by players in a round at once.",
			"minimum": 0,
			"maximum": 100,
			"default": 1
		},
		"starting_funds": {
			"title": "Ship Starting Funds",
			"Type": "integer",
			"description": "The amount of money a ship's bank account starts with",
			"minimum": 0,
			"maximum": 20000,
			"default": 2000
		},
		"omni_arpa": {
			"title": "Omni ARPA",
			"type": "boolean",
			"description": "If true, this ship's helm uses the classic ARPA: it sees the real names of all ships at range and has no label buttons. Intended for spy/artillery-type ships.",
			"default": false
		},
		"spawn_time_coeff": {
			"title": "Required Spawn Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value SHIP_SPAWN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn this ship from the join menu.",
			"minimum": 0,
			"default": 1
		},
		"officer_time_coeff": {
			"title": "Required Officer Playtime Coefficient",
			"type": "number",
			"description": "A multiplier used, along with the config value OFFICER_JOIN_BASE_EXP_MIN, to determine the amount of time a player must have spent as Living to spawn as an officer job on this ship AFTER it has been spawned.",
			"minimum": 0,
			"default": 1
		},
		"enabled": {
			"title": "Selectable",
			"type": "boolean",
			"description": "Whether or not this ship can be selected by players. Will still be admin-spawnable if not.",
			"default": false
		},
		"space_spawn": {
			"title": "Spawns in space",
			"type": "boolean",
			"description": "Whether this ship will spawn in space or at the outpost. If true, the ship will be placed randomly in space upon being spawned by the join menu.",
			"default": false
		}
	},

	"required": [
		"map_name",
		"map_short_name",
		"map_path",
		"faction",
		"job_slots"
	]
}

=== SOLARIS-Collective/Solaris/_maps/_modular_solaris/configs/nanotrasen_delta.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_modular_solaris/ship_config_schema.json",
	"map_name": "Delta-class Frigate",
	"map_short_name": "Delta",
	"description": "Судно класса 'Delta' - это компактное и современное шахтерское судно, которое дополняет свой сравнительно небольшой органический экипаж полным набором робототехнических средств, включая ИИ и множество шахтерских и логистических дронов и киборгов. Несмотря на то, что Delta очень любимы логистами Нанотрейзен за их минимальное обслуживание и высокую экономическую эффективность, они гораздо менее популярны среди экипажей, выбранных для управления ими, так как им сильно не хватает мест для размещения экипажа и оборонительного вооружения.",
	"map_path": "_maps/_modular_solaris/shuttles/nanotrasen/nanotrasen_delta.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"starting_funds": 4000,
	"prefix": "NTDSV",
	"faction": "/datum/faction/nt",
	"tags": [
		"Исследовательский"
	],
	"namelists": [
		"GENERAL",
		"SPACE",
		"BRITISH_NAVY",
		"MERCANTILE",
		"NANOTRASEN"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/captain",
			"officer": true,
			"slots": 1
		},
		"Science Director": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/rd",
			"officer": true,
			"slots": 1
		},
		"Roboticist": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/scientist/deforest_researcher/roboticist",
			"slots": 2
		},
		"Mining Mech Pilot": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/miner",
			"slots": 1
		},
		"Engineer": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/engineer",
			"slots": 1
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/assistant",
			"slots": 1
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/independent_nemo.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Nemo-class Fauna Research Vessel",
	"map_short_name": "Nemo",
	"description": "Судно класса 'Nemo' - это судно мечты эксцентричного коллекционера, идеально подходящий для всех журналистов, антикваров и чудаков Фронтира. Здесь есть удобный кабинет, полноценная робототехническая мастерская (идеально подходящая для создания себе помощников!) и множество эзотерического оружия, подходящего для охоты на существ, которое можно установить над камином. Кроме того, на судне есть компактный, но функциональный медицинский отсек, достаточно хорошо спроектированный инженерный отсек и большое количество оборудования для добычи полезных ископаемых.",
	"map_path": "_maps/shuttles/independent/independent_nemo.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 10,
	"starting_funds": 500,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
		"Инженерный",
		"ИИ",
		"Исследовательский"
	],
	"namelists": [
		"NATURAL",
		"NATURAL_AGGRESSIVE",
		"SPACE"
	],
	"job_slots": {
		"Naturalist": {
			"outfit": "/datum/outfit/job/cel/independent/rd",
			"slots": 1
		},
		"Fauna Researcher": {
			"outfit": "/datum/outfit/job/cel/independent/scientist",
			"slots": 1
		},
		"Veterinary": {
			"outfit": "/datum/outfit/job/cel/independent/doctor",
			"slots": 1
		},
		"Fauna Hunter": {
			"outfit": "/datum/outfit/job/cel/independent/miner/scientist",
			"slots": 2
		},
		"Mech Pilot": {
			"outfit": "/datum/outfit/job/cel/independent/roboticist",
			"slots": 1
		},
		"Ship Engineer": {
			"outfit": "/datum/outfit/job/cel/independent/engineer",
			"slots": 1
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/cel/independent/assistant",
			"slots": 1
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_mankind/configs/nanotrasen_slasher.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_modular_mankind/ship_config_schema.json",
	"map_name": "Slasher-class ESW Vessel",
	"map_short_name": "Slasher",
	"description": "'Slasher' - новейший корабль раннего предупреждения Нанотрейзен, разработанный специально для дальней разведки своими мощнейшими сенсорами. Его выделяет огромная площадь покрытия солнечных панелей, ранее упомянутая дальность сенсоров, высокая удельная тяга, а также малый экипаж и достойная его квалификация - корабли обычно отдаются во власть Отдела по предотвращению потерь активов.",
	"map_path": "_maps/_modular_mankind/shuttles/nanotrasen/nanotrasen_slasher.dmm",
	"sensor_range": 8,
	"enabled": true,
	"limit": 1,
	"prefix": "NTBSV",
	"faction": "/datum/faction/nt",
	"tags": [
		"Боевой"
	],
	"namelists": [
		"NANOTRASEN",
		"BRITISH_NAVY"
	],
	"job_slots": {
		"Intelligence Officer": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/intel/captain",
			"officer": true,
			"slots": 1
		},
		"Security Operative": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/intel/operative",
			"slots": 1
		},
		"Medical Technician": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/intel/medic",
			"slots": 1
		},
		"Engineering Technician": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/intel/engineer",
			"slots": 1
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_mankind/configs/elysium_homafasher.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Homafasher-class Mining Corvette",
	"map_short_name": "Homafasher",
	"description": "По меркам шуры Аль-Фада, 'Хомафашер' — старый, но надёжный и проверенный временем корабль. Его история начинается на верфях Республики Элизиум, это корвет массового производства, с достаточно дешевым ценником для его габаритов. Этот звездолет используется буквально везде: начиная от гос. учреждений, заканчивая приватными компаниями. И, как не удивительно, сепаратистами. Вариантов судна очень много, но в случае с Хомафашер - это одна из самых дешевых версий, предназначенная для горнопромышленных целей и оснащенная базовым медицинским отсеком.",
	"map_path": "_maps/_modular_mankind/shuttles/elysium/elysium_homafasher.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 5,
	"prefix": "ESV",
	"faction": "/datum/faction/elysium",
	"tags": [
		"Боевой",
		"Шахтерский",
		"РП Фокус"
	],
	"namelists": [
		"SPACE",
		"WEAPONS"
	],
	"job_slots": {
		"Caid": {
			"outfit": "/datum/outfit/job/cel/elysium/captain",
			"officer": true,
			"slots": 1
		},
		"Mukatell": {
			"outfit": "/datum/outfit/job/cel/elysium/security",
			"slots": 2
		},
		"Ahisa`i": {
			"outfit": "/datum/outfit/job/cel/elysium/assistant",
			"slots" : 3
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_solaris/configs/independent_halftrack.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Halftrack-class Merchant Vessel",
	"map_short_name": "Halftrack",
	"description": "Редкое явление в Приграничье (но желанное), судно класса Halftrack - это сильно модернизированный вариант спасательного судна класса Li Tieguai, используемое в качестве передвижного магазина огнестрельного оружия предприимчивыми торговцами оружием повсюду. Если первоначальные варианты судна были скорее просто 'Li Tieguai', а медицинские приспособления были удалены и заменены оружейными стойками и шкафами для боеприпасов, то современная версия 'Halftrack' оснащена стрельбищем, сертифицированной службой безопасности InteQ и централизованным торговым залом, идеальным для демонстрации товаров и одновременного обеспечения их безопасности. В ЩИТСПАВНЕ ПО ПРИЧИНЕ: ШИП НАХОДИТЬСЯ НА ДОРАБОТКЕ БАЛАНСА! Оутфиты сломаны!",
	"map_path": "_maps/_modular_solaris/shuttles/independent/independent_halftrack.dmm",
	"enabled": false,
	"limit": 1,
	"sensor_range": 4,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": [
	"Торговый",
	"РП Фокус"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/independent/captain",
			"slots": 1
		},
		"IRMG Vanguard": {
			"outfit": "/datum/outfit/job/inteq/captain",
			"officer": true,
			"slots": 1
		},
		"IRMG Enforcer": {
			"outfit": "/datum/outfit/job/inteq/security",
			"slots": 2
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/independent_bubble.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Bubble-class Colonial Ship",
	"map_short_name": "Bubble",
	"map_path": "_maps/shuttles/independent/independent_bubble.dmm",
	"description": "В то время как самые известные судна-колонии были громадными, высокоразвитыми кораблями, предназначенными для переправки сотен, а то и тысяч поселенцев в далекие миры и создания городов за считанные месяцы - Каликсианский Лунный свет, Кандор, Первый поезд в Форт-Сол, - судно класса 'Bubble' предназначен для тех, кто хочет основать небольшое ранчо или деревню на просторах космоса. Bubble очень компактны, но оснащены всем необходимым для создания колонии - обширным научно-исследовательским оборудованием, надежной добывающей техникой и карго подом для быстрой продажи культуры/руды и других продуктов от производства колонии. Несмотря на то, что исторически корабли класса 'Bubble' использовались Соларианской Федерацией для создания колоний, их собственная версия недавно была снята с эксплуатации.",
	"enabled": true,
	"limit": 1,
	"sensor_range": 6,
	"prefix": "ISV",
	"faction": "/datum/faction/independent",
	"tags": ["Исследовательский"],
	"namelists": [
		"GENERAL",
		"SPACE"
	],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/independent/captain",
			"slots": 1
		},
		"Scientist": {
			"outfit": "/datum/outfit/job/cel/independent/scientist",
			"slots": 1
		},
		"Engineer": {
			"outfit": "/datum/outfit/job/cel/independent/engineer",
			"slots": 1
		},
		"Miner": {
			"outfit": "/datum/outfit/job/cel/independent/miner",
			"slots": 1
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/cel/independent/assistant",
			"slots": 3
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/configs/independent_junker.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_mod_celadon/ship_config_schema.json",
	"map_name": "Junker-class Salvaged Ship",
	"map_short_name": "Junker",
	"description": "Судно класса 'Junker' - это не официальный класс, а скорее название общей группы суден, созданных из руин старых суден или станций. Эти судна стали обычным явлением во время ICW, когда дезертиры бежали из зон конфликта на этих 'Junker's', не готовые к трудностям космической жизни. С тех пор они стали редкостью, а немногие выжившие экипажи этих суден обычно испытывают чувство презрения к обычным властным структурам и, как правило, не имеют определенного капитана или даже владельца судна.",
	"map_path": "_maps/shuttles/independent/independent_junker.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 7,
	"starting_funds": 0,
	"prefix": "SV",
	"faction": "/datum/faction/independent",
	"tags": ["Выживание"],
	"namelists": [
		"GENERAL",
		"SPACE"
	],
	"job_slots": {
		"Assistant": {
			"outfit": "/datum/outfit/job/cel/independent/assistant",
			"slots": 4
		}
	}
}

=== SOLARIS-Collective/Solaris/_maps/_modular_mankind/configs/nanotrasen_venture.json
{
	"$schema": "https://raw.githubusercontent.com/CeladonSS13/Shiptest/beta-dev/_maps/_modular_mankind/ship_config_schema.json",
	"map_name": "Venture-class Exploration Shuttle",
	"map_short_name": "Venture",
	"description": "Небольшой шахтерский шатл для поддержки флота. Создан для обслуживания и технической поддержки более крупных судов. Данный экземпляр производства Нанотрейзен. Расчитан для кофмортной работы экипажа из двух человек.",
	"map_path": "_maps/_modular_mankind/shuttles/nanotrasen/nanotrasen_venture.dmm",
	"enabled": true,
	"limit": 1,
	"sensor_range": 4,
	"starting_funds": 2000,
	"prefix": "NTDSV",
	"faction": "/datum/faction/nt",
	"tags": ["Шахтерский"],
	"namelists": ["NANOTRASEN"],
	"job_slots": {
		"Captain": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/captain/nslogistics",
			"officer": true,
			"slots": 1
		},
		"Assistant": {
			"outfit": "/datum/outfit/job/cel/nanotrasen/assistant/nslogistics",
			"slots": 1
		}
	}
}
